global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-prometheus-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
    - job_name: 'cadvisor'
      static_configs:
          - targets: ['cadvisor:8080']


rule_files:
    - 'prometheus.rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /
      static_configs:
        - targets: ['alertmanager:9093']
